#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

if [ ! -e ./bin/cowcheck ]; then
    ./scripts/build
fi

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/cowcheck .
docker build -t ${REPO}/cowcheck:${TAG} .

echo Built ${REPO}/cowcheck:${TAG}
